### PR TITLE
Correcting main path

### PR DESCRIPTION
**Pull request by de314**
I am currently  having to use the following as a work around

```
import { Algorithm, Operators } from 'microverse/src'
const { Crossovers, Selectors } = Operators
```

### CODE REVIEW

**Comment by muliyul** [comment]
`lib` folder exists when you install the package through npm. Are you trying to use it via cloning?

**Comment by de314** [comment]
You might have published the wrong version.

```
________________________________________________________________________________
| ~/workspace/tmp @ bc-desposito-mbp-6976 (davidesposito) 
| => npm --version
3.10.8
________________________________________________________________________________
| ~/workspace/tmp @ bc-desposito-mbp-6976 (davidesposito) 
| => npm i microverse
tmp@1.0.0 /Users/davidesposito/workspace/tmp
└─┬ microverse@1.1.0 
  ├─┬ async@2.6.0 
  │ └── lodash@4.17.4 
  └── bluebird@3.5.1 

npm WARN tmp@1.0.0 No description
npm WARN tmp@1.0.0 No repository field.
________________________________________________________________________________
| ~/workspace/tmp @ bc-desposito-mbp-6976 (davidesposito) 
| => ll node_modules/microverse/
total 40
-rw-r--r--  1 davidesposito  staff   1.0K Mar  9  2017 .npmignore
-rw-r--r--  1 davidesposito  staff    48B Mar 13  2017 .travis.yml
drwxr-xr-x  5 davidesposito  staff   160B Nov 27 08:45 example/
-rw-r--r--  1 davidesposito  staff    19K Mar 13  2017 logo.png
-rw-r--r--  1 davidesposito  staff   496B Mar  9  2017 microverse.iml
-rw-r--r--  1 davidesposito  staff   2.3K Nov 27 08:45 package.json
-rw-r--r--  1 davidesposito  staff   3.5K Mar 13  2017 readme.md
drwxr-xr-x  5 davidesposito  staff   160B Nov 27 08:45 src/
drwxr-xr-x  5 davidesposito  staff   160B Nov 27 08:45 test/
```

This is a clean npm install with no `lib` folder. I encourage you to try it out yourself.

**Comment by de314** [comment]
But if it makes any different to you, I decided not to use your package anyway. Thanks for publishing this. It was useful to get started.

**Comment by muliyul** [comment]
I might be interested in doing a complete rewrite in typescript (this was basically me testing npm). Will you be interested in taking part of it?

**Comment by de314** [comment]
No thanks, I am not a huge fan of type script. If I am willing to use something strongly typed, then I would rather use Java or some C variant. Also, it would be nice if it was Node/Browser friendly so that it could be used for heavy computation on the server, or lightweight optimization problems in the browser.

If you are going to re-write it, a couple lacking features that I found were
- `seed` for a random number generator so that you can reproduce test cases. The random number generator should be available to `selector/mutator/crossover/...` functions.
- `elitism` percentage to decide how many of the fittest genes should state in the population
- `steadyState` should include a percentage and selection mechanism for how to keep/kill genes
-  `stopCriteria` should return a `state` object that includes things like `generation`, `runDuration`, `fitnessMean/Median/Variance/StdDev`
- high level options like `maxIterations`, `maxDuration`
- Add additional selectors e.g. [`Tournament`](https://en.wikipedia.org/wiki/Tournament_selection), `UniformRandom`, [`StochasticUniversal`](https://en.wikipedia.org/wiki/Stochastic_universal_sampling)
  - possibly with `Tournament2`, `Tournament3`, and `TournamentN` for convenience

**Pull request merged**
